---
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3

  children:
    k3s_server:
      hosts:
        node-94:
          ansible_host: 192.168.178.94
          k3s_role: server

    k3s_agent:
      hosts:
        node-95:
          ansible_host: 192.168.178.95
          k3s_role: agent
          hdd_mount_path: /mnt/hdd
          hdd_device: /dev/sda

    k3s_cluster:
      children:
        k3s_server: {}
        k3s_agent: {}
