---
# argocd/apps/gitlab/Chart.yaml
apiVersion: v2
name: gitlab
description: GitLab CE – gitlab.pke-lab.de – Storage auf Node 95 HDD
type: application
version: 0.1.0
dependencies:
  - name: gitlab
    version: ">=7.11.0"
    repository: https://charts.gitlab.io
